language: php
php:
  - '7.0'
install:
  - composer install
before_script:
  - cp phpunit.xml.dist phpunit.xml
script:
  - ./vendor/bin/phpcs --standard=PSR2 --colors --report=summary --extensions=php,inc,lib --ignore=vendor ./
  - ./vendor/bin/phpunit --debug
